test:
	javac -cp .:junit.jar:hamcrest.jar *.java
	java -cp .:junit.jar:hamcrest.jar Main
	cat RESULTS.txt

submit:
	git add ./*
	git commit -m "Autogenerated Makefile Submit: `date`"
	git push

hello:
	javac HelloWorld.java
	java HelloWorld

clean:
	rm -rf *.class
	rm -rf RESULTS.txt